name: aws credentials
on:
    workflow_call:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: aws access key
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: aws access key
        required: true
      AWS_REGION:
        description: aws region
        required: true


jobs: 
    aws-login:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ inputs.AWS_REGION }}
            - name: aws-login-test
              run: aws sts get-caller-identity

